<?php

/**
 * Implementation of hook_menu().
 */
function poof_menu() {
  $items['poof'] = array(
    'title' => 'Ahah!',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('poof_form'),
    'access arguments' => array('access content')
  );
  $items['poof/message_js'] = array(
    'page callback' => 'poof_message_js',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content')
  );
  $items['poof/interval_js'] = array(
    'page callback' => 'poof_interval_js',
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
  );

  return $items;
}

/**
 * Form definition.
 */
function poof_form() {
  $form['target'] = array(
    '#type' => 'markup',
    '#prefix' => '<div id="target">',
    '#value' => t('Click the button below. I dare you.'),
    '#suffix' => '</div>',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Click Me'),
    '#ahah' => array(
      'event' => 'click',
      'path' => 'poof/message_js',
      'wrapper' => 'target',
      'effect' => 'fade',
    ),
  );
  // Uncomment below to try the progress bar.
  /*
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Click Me'),
    '#ahah' => array(
      'event' => 'click',
      'path' => 'poof/message_js',
      'wrapper'=>'target',
      'effect' => 'fade',
      'progress' => array(
        'type'=>'bar',
        'message'=>t('One moment...'),
        'interval'=>2,
        'url' => 'poof/interval_js',
      ),
    ),
  );
  // */
  return $form;
}

/**
 * Menu callback for AHAH additions.
 */
function poof_message_js() {
  $output = t('POOF!');
  
  // Uncomment below for the progress bar.
  /*
  for ($i = 0; $i < 100; $i = $i + 20) {
    // Record how far we are.
    variable_set('poof_percentage', $i);
    // Simulate performing a task by waiting 2 seconds.
    sleep(2);
  }
  // */
  drupal_json(array('status' => TRUE, 'data' => $output));
}

/**
 * Menu callback for AHAH progress bar intervals.
 */
function poof_interval_js() {
  // Read how far we are.
  $percentage = variable_get('poof_percentage', 0);
  // Return the value to the JavaScript progress bar.
  drupal_json(array('percentage' => $percentage));
}
